print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/eliaskassellraymond/Documents/GitHub/Manhattan-Hololens/Assets/objects/urinal.mb"`)
{		
	file -o "/Users/eliaskassellraymond/Documents/GitHub/Manhattan-Hololens/Assets/objects/urinal.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/eliaskassellraymond/Documents/GitHub/Manhattan-Hololens/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/eliaskassellraymond/Documents/GitHub/Manhattan-Hololens/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/eliaskassellraymond/Documents/GitHub/Manhattan-Hololens/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
